#!/usr/bin/env bash
# Bash script to run a process indefinitely with a sleep of 2 between each iteration
# Displays "To infinity and beyond indefinitely"
# Displays "I am invincible!!!" when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
