#!/usr/bin/env bash

# This script displays the content of the file /etc/passwd, showing the username, user ID, and home directory path for each user.

while IFS=':' read -r username password uid gid info homedir shell
do
  echo "Username: $username"
  echo "User ID: $uid"
  echo "Home directory: $homedir"
done < /etc/passwd
