#!/usr/bin/env bash

# This script displays the content of the file /etc/passwd, using the while loop and IFS to format the output.

while IFS=':' read -r username password uid gid info homedir shell
do
  group=$(grep ":$gid:" /etc/group | cut -d':' -f1)
  command=$(which "${shell}" | awk -F '/' '{print $NF}')
  echo "The user $username is part of the $group gang, lives in $homedir and rides $command."
  echo "User ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd

