#!/usr/bin/env bash
# This script configures the SSH client

Host *
  PasswordAuthentication no
  IdentifyFile ~/.ssh/school
  SendEnv LANG LC_*
  HashKnownHosts yes
  GSSAPIAuthentication yes
  GSSAPIDelegateCredentials no
